### ISSUE TITLE
ANARI 1.0 Provisional Specification typos and missing info

### ISSUE THREAD

**Issue by player1537** [KhronosGroup/ANARI-Docs#14]
I noticed some typos and missing information in the ANARI 1.0 provisional specification document:

* In Section 4.8, Table 7, there are mistakenly 4 columns instead of 3 which causes the table to be incorrectly formatted.
* In Section 3.6, the `ANARIDataType` `ANARI_SPATIAL_FIELD` should be included in the list of allowed data types for `anariGetObjectSubtypes`.
* In Section 3.6, there is no explanation of how to call `anariGetObjectParameters` for objects which have no subtype (e.g. Group, Instance, World, Surface).
  * (I presume that passing `NULL` as the `objectSubtype` is the intention, but it's not explained in the text).
* I don't know if it's feasible, but currently there's no way to tell what type of `ANARI_ARRAY{1,2,3}D` is expected based on `anariGetObjectParameter` without reading the source code or documentation for the library you're using. Perhaps a future version of the spec could allow for this, for example, something like `ANARI_ARRAY1D_OF(ANARI_LIGHT)`.

**Edit:** Found a couple others:

* The spec makes reference to `ANARI_FLOAT32_MAT4x4` (e.g. Section 6.2.1 `inTransform` and `outTransform`) but this type isn't defined in Section 3.5 Table 1 (`FLOAT32_MAT4` is but not `MAT4x4`).
  * It's also a little unclear what `ANARI_FLOAT32_MAT3x4` is supposed to be. The current description is "three by four 32 bit float matrix in column major order" but a better description might be "three rows by four columns 32 bit float matrix in column major order." I realized that my confusion was because the description says it's "column major order" (in terms of the data) but then the dimensions are still listed in row major order.

**Comment by johguenther** [comment]
Thanks for the feedback! Some of the issues have already been [reported](https://github.com/KhronosGroup/ANARI-Docs/issues/2) (and https://github.com/KhronosGroup/ANARI-Docs/issues/6) and [fixed](https://github.com/KhronosGroup/ANARI-Docs/pull/3) (plus https://github.com/KhronosGroup/ANARI-Docs/pull/12), but we indeed need to update the documents in https://github.com/KhronosGroup/ANARI-Registry/blob/main/specs/1.0-provisional/ to reflect those changes.

I'll add `ANARI_SPATIAL_FIELD`.

Is it expected or useful to use `anariGetObjectParameters` for objects without subtype &ndash; their parameters are known per spec? Then using `NULL` for `objectSubtype` could be an option, otherwise we could disallow the call for those object types (similarly as for `anariGetObjectSubtypes`).

The parameter introspection indeed has gaps: for non-trivial (nested) types like you describe and also for type aliases (when different types with the same name are allowed). We have some ideas for the latter, but generically supporting the first is hard.
